name: Automatic Deployment
on:
  push:
    branches:
    - prod

jobs:
  automatic_deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
    - uses: 'actions/setup-node@master'
      with:
        node-version: 14
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run Unit Tests
      run: npm run test:unit

    - name: Build Production Code
      run: npm run build
    
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
  
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'

    - id: findandreplace
      name: Prepare Version Name for GAE Deployment
      uses: mad9000/actions-find-and-replace-string@2
      with:
        source: '${{ steps.package-version.outputs.current-version}}'
        find: '.'
        replace: '-'

    - name: Deploy to App Engine
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: 'app.yaml'
        promote: true
        version: '${{ steps.findandreplace.outputs.value }}'
    
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: 'production'
        version: '${{ steps.package-version.outputs.current-version}}'
        sourcemaps: 'dist/js'

    - id: remove
      name: Remove old GAE versions
      uses: Reviewable/appengine-remove-action@v2.1.2
      with:
        limit: 3